name: ci-fullstack-workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  push:
    branches:
      - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: cd backend && npm install

      - name: Run Tests
        run: cd backend && npm test

      - name: Lint Code
        run: cd backend && npm run lint

      - name: Print Completion Message
        run: echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at ${{ github.event.created_at }}."
